/*
 * displays winner and exit button, play again button. Check doc for more info.
 */
package GUI;
import Main.Game;

/**
 *
 * @author brand
 */
public class WinnerScreen extends javax.swing.JFrame {
    
    private String winner;
    private boolean playAgain;

    /**
     * Creates new form WinnerScreen
     */
    public WinnerScreen() {
        winner = "";
        playAgain = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        nameOfWinner = new javax.swing.JTextField();
        congratsLabel = new javax.swing.JLabel();
        theWinnerLabel = new javax.swing.JLabel();
        totalMoneyLabel = new javax.swing.JLabel();
        totalPropertiesLabel = new javax.swing.JLabel();
        exitGameButton = new javax.swing.JButton();
        playAgainButton = new javax.swing.JButton();
        moneyEmblem = new javax.swing.JLabel();
        playersTotalMoney = new javax.swing.JTextField();
        playersTotalProperties = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameOfWinner.setEditable(false);
        nameOfWinner.setFont(new java.awt.Font("Engravers MT", 1, 56)); // NOI18N
        nameOfWinner.setForeground(new java.awt.Color(153, 0, 0));
        nameOfWinner.setText("You are");
        nameOfWinner.setBorder(null);
        nameOfWinner.setOpaque(false);
        jLayeredPane1.add(nameOfWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        congratsLabel.setFont(new java.awt.Font("Engravers MT", 1, 56)); // NOI18N
        congratsLabel.setForeground(new java.awt.Color(153, 0, 0));
        congratsLabel.setText("Congrats!");
        jLayeredPane1.add(congratsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        theWinnerLabel.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        theWinnerLabel.setForeground(new java.awt.Color(153, 0, 0));
        theWinnerLabel.setText("Total Properties:");
        jLayeredPane1.add(theWinnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 370, -1, -1));

        totalMoneyLabel.setFont(new java.awt.Font("Engravers MT", 1, 56)); // NOI18N
        totalMoneyLabel.setForeground(new java.awt.Color(153, 0, 0));
        totalMoneyLabel.setText("The Winner!");
        jLayeredPane1.add(totalMoneyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        totalPropertiesLabel.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        totalPropertiesLabel.setForeground(new java.awt.Color(153, 0, 0));
        totalPropertiesLabel.setText("total Money:");
        jLayeredPane1.add(totalPropertiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, -1, -1));

        exitGameButton.setBackground(new java.awt.Color(153, 0, 0));
        exitGameButton.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        exitGameButton.setForeground(new java.awt.Color(255, 255, 255));
        exitGameButton.setText("Exit Game");
        exitGameButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitGameButton.setPreferredSize(new java.awt.Dimension(250, 100));
        exitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(exitGameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 720, 370, -1));

        playAgainButton.setBackground(new java.awt.Color(153, 0, 0));
        playAgainButton.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        playAgainButton.setForeground(new java.awt.Color(255, 255, 255));
        playAgainButton.setText("Play Again");
        playAgainButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        playAgainButton.setPreferredSize(new java.awt.Dimension(250, 100));
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(playAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, 370, -1));

        moneyEmblem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money emblem red.png"))); // NOI18N
        jLayeredPane1.add(moneyEmblem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 170, -1, -1));

        playersTotalMoney.setEditable(false);
        playersTotalMoney.setFont(new java.awt.Font("Engravers MT", 1, 54)); // NOI18N
        playersTotalMoney.setForeground(new java.awt.Color(0, 0, 0));
        playersTotalMoney.setText("0");
        playersTotalMoney.setBorder(null);
        playersTotalMoney.setOpaque(false);
        playersTotalMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playersTotalMoneyActionPerformed(evt);
            }
        });
        jLayeredPane1.add(playersTotalMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 170, -1, -1));

        playersTotalProperties.setEditable(false);
        playersTotalProperties.setFont(new java.awt.Font("Engravers MT", 1, 54)); // NOI18N
        playersTotalProperties.setForeground(new java.awt.Color(0, 0, 0));
        playersTotalProperties.setText("0");
        playersTotalProperties.setBorder(null);
        playersTotalProperties.setOpaque(false);
        playersTotalProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playersTotalPropertiesActionPerformed(evt);
            }
        });
        jLayeredPane1.add(playersTotalProperties, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 350, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winner screen background.png"))); // NOI18N
        background.setText("jLabel1");
        jLayeredPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playersTotalPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playersTotalPropertiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playersTotalPropertiesActionPerformed

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        
     //   Main main = new Main();
        playAgain = true;
        dispose();
        
        
        
    /*    MainMenu MM = new MainMenu();
        MM.setVisible(true);
        dispose(); */
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void playersTotalMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playersTotalMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playersTotalMoneyActionPerformed

    private void exitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitGameButtonActionPerformed

    /**
     * Sets the name of the winner.
     * @param name 
     */
    public void setWinner(String name, int money, int properties){
        winner = name;
        playersTotalMoney.setText(""+money);
        playersTotalProperties.setText(""+properties);
        nameOfWinner.setText(winner);
    }
    
    public boolean getPlayAgain(){
        return playAgain;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinnerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel congratsLabel;
    private javax.swing.JButton exitGameButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel moneyEmblem;
    private javax.swing.JTextField nameOfWinner;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JTextField playersTotalMoney;
    private javax.swing.JTextField playersTotalProperties;
    private javax.swing.JLabel theWinnerLabel;
    private javax.swing.JLabel totalMoneyLabel;
    private javax.swing.JLabel totalPropertiesLabel;
    // End of variables declaration//GEN-END:variables
}
